#!/bin/sh
# Automatically take screenshot of all app icons
#
# Shortcomings:
# * OS == 10.6 my version could not `screencapture` so I used the `Skitch` app
# * OS <= 10.5 has no `qlmanage -x` --> cant generate thumbnails 
# * OS <= 10.3 has no Finder icon preview for `.icns` --> open all in Preview
# * OS <= 10.2 wont open "broken" `.icns` files in Preview
# * OS <= 10.1 has no `screencapture` --> but you can use `Cmd + Shift + 3`
# * OS <= 10.0 has no `Cmd + Shift + 3` --> /Applications/Utilities/Grab

if [ ! "$1" -gt 0 ]; then
	echo "usage: $(basename "$0") <sleep>"
	echo
	echo '<sleep>: wait sec between screenshots to allow macOS to render icons'
	exit 0
fi

SLEEP=$1
FINDER_OPEN=false

# $1: "true" | "false"
dock_hide() {
	osascript -e "tell application \"System Events\" to set autohide of dock preferences to $1" > /dev/null
}

close_finder() {
	osascript -e 'tell application "Finder" to close front window' > /dev/null
	FINDER_OPEN=false
}

# $1: destination-dir (type), $2: source-files (.app)
render_quicklook() {
	dst_dir=$1
	src=$2
	name=$(basename "$src")
	dst_file="$dst_dir/$name.png"
	# skip already existing
	if [ -e "$dst_file" ]; then
		return
	fi
	mkdir -p "$dst_dir"
	qlmanage -x -t -s "${name%%-*}" "$src" -o "$dst_dir" > /dev/null
	if [ ! -e "$dst_file" ]; then
		touch "$dst_file"
	fi
}

render_all_icns() {
	for IN in "$indir/icns/"*/; do
		typ=$(basename "$IN")
		OUT=$outdir/icns/$typ
		echo "quicklook thumbnails for $typ"
		for src in "$IN"*; do
			render_quicklook "$OUT" "$src"
		done
	done
}

# $1: destination-file (.png), $2: DS_Store size, $3-: source-files (.app)
render_app() {
	dst=$1
	size=$2
	shift 2
	# skip already existing
	if [ -e "$dst" ]; then
		return
	fi
	rm -rf tmp
	mkdir -p tmp/render
	cp -R "$@" tmp/render 2> /dev/null
	if [ -z "$(ls tmp/render)" ]; then
		return
	fi
	echo "wait for screenshot $dst"
	cp "assets/dsstore-$size" tmp/.DS_Store
	sleep 0.5
	open tmp/render
	FINDER_OPEN=true
	sleep "$SLEEP"
	mkdir -p "$(dirname "$dst")"
	screencapture -t png "$dst"
	# close Finder window to allow DS_Store config reset
	close_finder
	sleep 0.5
}

render_all_app_variants() {
	for IN in "$indir/app/"*/; do
		OUT=$outdir/app/$(basename "$IN")
		render_app "$OUT/0-sm.png" 128 "$IN"{16,18,24,32,36,48,64}-*
		render_app "$OUT/128.png" 256 "$IN"128-*
		render_app "$OUT/256.png" 256 "$IN"256-*
		render_app "$OUT/512-ic09.png" 512 "$IN"512-ic09*
		render_app "$OUT/512-ic14.png" 512 "$IN"512-ic14*
		render_app "$OUT/1024-ic10.png" 512 "$IN"1024-ic10*
	done
	echo 'done.'
}

show_notice() {
	echo 'Warning:'
	echo ' - Dont interact with the UI in the next 10 minutes.'
	echo ' - Disable all screensavers!'
	echo ' - Make sure Terminal has Screen Recording capability'
	# just to trigger security popup
	osascript -e 'tell application "Finder" to id of window 1' > /dev/null 2> /dev/null
	screencapture -c -x || echo ''

	echo 'ready? press enter to continue '
	read -r _
	echo
	echo 'Automatic screenshot in progress ...'
}


###################
# Main entry point
###################

indir=input
outdir=out-rendered
mkdir -p "$outdir"

echo 'generate quicklook thumbnail icons ...'

# qlmanage icns thumbnails

if [ ! -d "$outdir/app" ]; then
	render_all_icns
fi

# Hide Dock

dock_hide 'true'

on_exit() {
	dock_hide 'false'
	$FINDER_OPEN && close_finder
	rm -rf tmp
	exit
}
trap on_exit INT

# Start screenshotting

show_notice
render_all_app_variants

# export

rm -f out-rendered.zip
zip -o out-rendered.zip -r out-rendered/

on_exit
