#!/bin/sh
# Automatically take screenshot of all app icons
#
# Shortcomings:
# * OS == 10.6 my version could not `screencapture` so I used the `Skitch` app
# * OS <= 10.5 has no `qlmanage -x -o` --> cant generate thumbnails 
# * OS <= 10.4 has no `qlmanage` at all
# * OS <= 10.3 has no Finder icon preview for `.icns` --> open all in Preview
# * OS <= 10.2 wont open "broken" `.icns` files in Preview
# * OS <= 10.1 has no `screencapture` --> but you can use `Cmd + Shift + 3`
# * OS <= 10.0 has no `Cmd + Shift + 3` --> /Applications/Utilities/Grab
#
# 10.3 and 10.2 create screenshots in PDF format, 10.1 and 10.0 in TIFF

if [ $# != 1 ] || [ ! "$1" -gt 0 ]; then
	echo "usage: $(basename "$0") <sleep>"
	echo
	echo '<sleep>: wait sec between screenshots to allow macOS to render icons'
	exit 0
fi

SLEEP=$1
FINDER_OPEN=false

# $1: "true" | "false"
dock_hide() {
	osascript -e "tell application \"System Events\" to set autohide of dock preferences to $1" > /dev/null
}

close_finder() {
	osascript -e 'tell application "Finder" to close front window' > /dev/null
	FINDER_OPEN=false
}

# $1: destination-dir (type), $2: source-files (.app), [$3: scale]
render_quicklook() {
	dst_dir=$1
	src=$2
	name=$(basename "$src")
	dst_file="$dst_dir/$name.png"
	# skip already existing
	if [ -e "$dst_file" ]; then
		return
	fi
	# retina scaling
	size=${name%%-*}
	if [ -z "$3" ]; then
		qlmanage -x -t -s "$size" "$src" -o "$dst_dir" > /dev/null
	else
		qlmanage -x -t -s "$size" -f "$3" "$src" -o "$dst_dir" > /dev/null
	fi
	if [ ! -e "$dst_file" ]; then
		touch "$dst_file"
	fi
}

render_all_icns() {
	for IN in "$indir/icns/"*/; do
		typ=$(basename "$IN")
		OUT=$outdir/icns/$typ
		echo "quicklook thumbnails for $typ"
		mkdir -p "$OUT"
		for src in "$IN"*; do
			render_quicklook "$OUT" "$src"
		done
		# render @2x
		if [ "$typ" = 'retina' ]; then
			echo "quicklook thumbnails for retina @2x"
			mkdir -p "$OUT@2x"
			for src in "$IN"*; do
				render_quicklook "$OUT@2x" "$src" 2
			done
		fi
	done
}

# $1: destination-file (.png), $2: DS_Store size, $3-: source-files (.app)
render_app() {
	dst=$1
	size=$2
	shift 2
	# skip already existing
	if [ -e "$dst" ]; then
		return
	fi
	rm -rf .DS_Store tmp/
	sleep 0.2
	mkdir -p tmp/render
	if [ -z "$(ls "$@" 2> /dev/null)" ]; then
		return
	fi
	cp "assets/dsstore-$size" tmp/.DS_Store
	sleep 0.2
	open tmp/render
	FINDER_OPEN=true
	echo "wait for screenshot $dst"
	sleep 0.5
	cp -R "$@" tmp/render 2> /dev/null
	sleep "$SLEEP"
	mkdir -p "$(dirname "$dst")"
	screencapture "$dst"
	rm -rf tmp/render/*
	sleep 0.2
	# close Finder window to allow DS_Store config reset
	close_finder
}

render_all_app_variants() {
	for IN in "$indir/app/"*/; do
		OUT=$outdir/app/$(basename "$IN")
		render_app "$OUT/0-sm.png" 128 "$IN"16-* "$IN"18-* "$IN"24-* "$IN"32-* "$IN"36-* "$IN"48-* "$IN"64-* 
		render_app "$OUT/128.png" 256 "$IN"128-*
		render_app "$OUT/256.png" 256 "$IN"256-*
		render_app "$OUT/512-ic09.png" 512 "$IN"512-ic09*
		render_app "$OUT/512-ic14.png" 512 "$IN"512-ic14*
		render_app "$OUT/1024-ic10.png" 512 "$IN"1024-ic10*
	done
	echo 'done.'
}

render_all_app_edge_cases() {
	for IN in "$indir/app/"*/; do
		fn=$(basename "$IN")
		if [ "$fn" = 'alpha-precedence' ]; then
			SIZE=96
		else
			SIZE=128
		fi
		render_app "$outdir/app/$fn.png" $SIZE "$IN"*.app
	done
	echo 'done.'
}

show_notice() {
	echo 'Warning:'
	echo ' - Dont interact with the UI in the next 10 minutes.'
	echo ' - Disable all screensavers!'
	echo ' - Make sure Terminal has Screen Recording capability'
	# just to trigger security popup
	osascript -e 'tell application "Finder" to id of window 1' > /dev/null 2> /dev/null
	screencapture -c -x || echo ''

	echo 'ready? press enter to continue '
	read -r _
	echo
	echo 'Automatic screenshot in progress ...'
}


###################
# Main entry point
###################

indir=input
outdir=out
mkdir -p "$outdir"

echo 'generate quicklook thumbnail icons ...'

# qlmanage icns thumbnails

if [ ! -d "$outdir/app" ]; then
	render_all_icns
fi

# Hide Dock

dock_hide 'true'

on_exit() {
	dock_hide 'false'
	$FINDER_OPEN && close_finder
	rm -rf tmp
	echo 'exit.'
	exit
}
trap on_exit INT HUP TERM

# Start screenshotting

show_notice

if [ -d "$indir/app/retina" ]; then
	render_all_app_edge_cases
else
	render_all_app_variants
fi

# export

echo 'write results.zip'
rm -f results.zip
zip -q -o results.zip -r out/

on_exit
